import { pgTable, text, integer, boolean, doublePrecision, jsonb, timestamp } from 'drizzle-orm/pg-core';

export const connectors = pgTable('connectors', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
  type: text('type').notNull(),
  enabled: boolean('enabled').default(false),
  config: jsonb('config'),
  lastSyncAt: timestamp('last_sync_at', { withTimezone: true }),
  syncCursor: text('sync_cursor'),
  syncFrequency: text('sync_frequency').default('6h'),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
  orgId: text('org_id').notNull().default('org_default'),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
});

export const syncJobs = pgTable('sync_jobs', {
  id: text('id').primaryKey(),
  connectorId: text('connector_id').notNull().references(() => connectors.id),
  status: text('status').notNull().default('pending'),
  startedAt: timestamp('started_at', { withTimezone: true }),
  completedAt: timestamp('completed_at', { withTimezone: true }),
  signalsPulled: integer('signals_pulled').default(0),
  signalsNew: integer('signals_new').default(0),
  error: text('error'),
  retryCount: integer('retry_count').default(0),
  cursor: text('cursor'),
  orgId: text('org_id').notNull().default('org_default'),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
});

export const themes = pgTable('themes', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
  description: text('description'),
  productArea: text('product_area'),
  strategicGoal: text('strategic_goal'),
  pm: text('pm'),
  jiraKey: text('jira_key'),
  jiraStatus: text('jira_status'),
  revenueImpact: integer('revenue_impact').default(0),
  strategicFit: integer('strategic_fit').default(0),
  competitiveDiff: integer('competitive_diff').default(0),
  signalFrequency: integer('signal_frequency').default(0),
  influencedARR: doublePrecision('influenced_arr').default(0),
  prototype: jsonb('prototype'),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
  orgId: text('org_id').notNull().default('org_default'),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
});

export const signals = pgTable('signals', {
  id: text('id').primaryKey(),
  externalId: text('external_id'),
  source: text('source').notNull(),
  connectorId: text('connector_id').references(() => connectors.id),
  title: text('title'),
  content: text('content'),
  account: text('account'),
  speaker: text('speaker'),
  arr: doublePrecision('arr').default(0),
  votes: integer('votes').default(0),
  category: text('category'),
  biasTag: text('bias_tag'),
  competitors: jsonb('competitors'),
  sentiment: text('sentiment'),
  aiSummary: text('ai_summary'),
  aiConfidence: doublePrecision('ai_confidence'),
  rawData: jsonb('raw_data'),
  sourceUrl: text('source_url'),
  syncJobId: text('sync_job_id').references(() => syncJobs.id),
  ingestedAt: timestamp('ingested_at', { withTimezone: true }).defaultNow(),
  biasConfidence: doublePrecision('bias_confidence'),
  biasReasoning: text('bias_reasoning'),
  classificationReasoning: text('classification_reasoning'),
  duplicateOf: text('duplicate_of'),
  needsReview: boolean('needs_review').default(false),
  classifiedAt: timestamp('classified_at', { withTimezone: true }),
  orgId: text('org_id').notNull().default('org_default'),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
});

export const themeSignals = pgTable('theme_signals', {
  id: text('id').primaryKey(),
  themeId: text('theme_id').notNull().references(() => themes.id),
  signalId: text('signal_id').notNull().references(() => signals.id),
  relevance: doublePrecision('relevance').default(1.0),
  assignedBy: text('assigned_by').default('manual'),
  orgId: text('org_id').notNull().default('org_default'),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
});

export const pipelineRuns = pgTable('pipeline_runs', {
  id: text('id').primaryKey(),
  status: text('status').notNull().default('pending'),
  startedAt: timestamp('started_at', { withTimezone: true }),
  completedAt: timestamp('completed_at', { withTimezone: true }),
  totalSignals: integer('total_signals').default(0),
  classifiedSignals: integer('classified_signals').default(0),
  biasDetectedSignals: integer('bias_detected_signals').default(0),
  embeddedSignals: integer('embedded_signals').default(0),
  error: text('error'),
  config: jsonb('config'),
  orgId: text('org_id').notNull().default('org_default'),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
});

export const reviewQueue = pgTable('review_queue', {
  id: text('id').primaryKey(),
  signalId: text('signal_id').notNull().references(() => signals.id),
  pipelineRunId: text('pipeline_run_id').references(() => pipelineRuns.id),
  reviewType: text('review_type').notNull(),
  status: text('status').notNull().default('pending'),
  aiSuggestedThemes: jsonb('ai_suggested_themes'),
  aiSuggestedBias: text('ai_suggested_bias'),
  aiConfidence: doublePrecision('ai_confidence'),
  currentThemeId: text('current_theme_id'),
  reviewerNotes: text('reviewer_notes'),
  reviewedBy: text('reviewed_by'),
  reviewedAt: timestamp('reviewed_at', { withTimezone: true }),
  orgId: text('org_id').notNull().default('org_default'),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
});

export const embeddingTracking = pgTable('embedding_tracking', {
  id: text('id').primaryKey(),
  signalId: text('signal_id').notNull().references(() => signals.id),
  embeddingModel: text('embedding_model').notNull().default('text-embedding-3-small'),
  chromadbId: text('chromadb_id'),
  contentHash: text('content_hash'),
  embeddedAt: timestamp('embedded_at', { withTimezone: true }),
  orgId: text('org_id').notNull().default('org_default'),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
});
